start: stmt+

stmt: expr ";"

     | var_decl ";"
     | if_stmt
     | loop_stmt
     | for_stmt

     | return_stmt ";"
     | break_stmt ";"
     | continue_stmt ";"
     | func_def

?body: stmt                 -> block
     | "{" stmt* "}"        -> block

if_stmt: matched_if
       | unmatched_if
matched_if: "if" logical_or body "else" body
unmatched_if: "if" logical_or body
            | "if" logical_or matched_if "else" unmatched_if

loop_stmt: "loop" body
for_stmt: "for" CNAME "in" expr ".." expr body

func_def: "fn" CNAME "(" [ parlist ] ")" [type_expr] block

parlist: param ("," param)*
param: CNAME ":" type_expr

function: "(" [ parlist ] ")" "=>" block

return_stmt: "return" [ expr ]
break_stmt: "break"
continue_stmt: "continue"

?type_expr: CNAME                            -> basic_type
         | "fn" "(" [ type_list ] ")"
         | "[" type_expr ";" INT "]"         -> list_type

block: ("{" stmt* "}")

type_list: type_expr ("," type_expr)*

POINTER: "*"
pointer_list: POINTER*

var_decl: "var" CNAME [ ":" pointer_list type_expr ] [ "=" expr ]    -> var_declaration
        | "static" CNAME [ ":" pointer_list type_expr ] [ "=" expr ] -> static_declaration
        | "const" CNAME [ ":" pointer_list type_expr ] "=" expr      -> const_declaration

?expr: assignment

?assignment: CNAME [ "[" expr "]" ] ASSIGN_OP expr     -> assign
           | logical_or

?logical_or:    logical_and ("||" logical_and)*
?logical_and:   comparison ("&&" comparison)*
?comparison:    term (COMP_OP term)*
?term:          factor (TERM_OP factor)*
?factor:        atom (FACT_OP atom)*

?atom       : "true"                 -> true
            | "false"                -> false

            | INT                    -> num
            | CNAME [ "[" expr "]" ] -> var

            | STRING                 -> str
            | CHAR                   -> char
            | list_literal           -> list_lit
            | list_repeated          -> list_rep

            | call
            | function

            | unop atom
            | "(" logical_or ")"

list_literal: "[" [ expr ("," expr)* ] "]"
list_repeated: "[" expr ";" INT "]"

call: CNAME "(" [ arglist ] ")"
arglist: expr ("," expr)*

INT       : /-?(0x[0-9a-fA-F_]+|0b[01_]+|[0-9_]+)/
CHAR      : /'([^\\\\']|\\\\.)'/

ASSIGN_OP: "=" | "+=" | "-=" | "*=" | "/=" | "%=" | "&=" | "|=" | "^=" | "<<=" | ">>="
COMP_OP   : "<=" | ">=" | "<" | ">" | "==" | "!="
TERM_OP   : "+" | "-" | ".."
FACT_OP   : "*" | "/" | "%" | "!" | "<<" | ">>"
unop      : "-" | "!"

%import common.CNAME
%import common.ESCAPED_STRING -> STRING
%import common.WS
%ignore WS
%ignore /\/\/[^\r\n]*/